name: BE deploy uat branch
run-name: BE deploy uat branch
on:
  push:
    branches:
      - 'uat'
    paths:
    - backend/**
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: [self-hosted,backend-server-staging] # tag in server-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          ls
          echo "Buil image"

  deploy:
    runs-on: [self-hosted,backend-server-staging] # tag in server-dev
    needs: [ build ]
    environment: uat
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          ls
          echo "Run image"